import { Nunito } from 'next/font/google';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import '../globals.css';

const inter = Nunito({ subsets: ['latin'], weight: ['300', '400', '500', '700', '900'] });

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				{children}
				<ToastContainer />
			</body>
		</html>
	);
}
